### ISSUE TITLE
用HttpClient请求Laravel Passport grant password获取token进程出现阻塞

### ISSUE THREAD

**Issue by jiangslee** [JieAnthony/laravel-octane-workerman#33]
php: 8.0.20
laravel/framework: v9.27.0
php cURL Information => 7.83.1

```
# LoginController.php 伪代码
class LoginController extend Controller{
    public function login(){
        $data = [
            'grant_type' => 'password',
            'client_id' => '1',
            'client_secret'=>'xxxx',
            'username'=>'admin',
            'password'=>'123456',
            'scope'=>''
        ];
        $res = Http::post(route('passport.token'), $data);
        // 上面的HttpClient获取本项目的token出现阻塞
        // 剩下的伪代码省略
    }
}
```

![image](https://user-images.githubusercontent.com/27892476/188055377-642053cf-bd47-425d-ac4c-c709383f8e99.png)

https://stackoverflow.com/questions/36947844/guzzlehttp-hangs-when-using-localhost

跟上面链接php artisan serve单线程问题有点相似，在nginx+php-fpm下是正常的，但在octane-workerman下也出现阻塞。

以下为报错日志：
```
} 
[2022-09-02 11:40:32] local.ERROR: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:7050/oauth/token {"exception":"[object] (Illuminate\\Http\\Client\\ConnectionException(code: 0): cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:7050/oauth/token at /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php:809)
[stacktrace]
#0 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Support/helpers.php(243): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#1 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(817): retry()
#2 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(686): Illuminate\\Http\\Client\\PendingRequest->send()
#3 /Users/hello/laravel/app/Qingwuit/Services/AuthService.php(75): Illuminate\\Http\\Client\\PendingRequest->post()
#4 /Users/hello/laravel/app/Http/Controllers/Auth/AuthController.php(17): App\\Qingwuit\\Services\\AuthService->login()
#5 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Auth\\AuthController->login()
#6 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#7 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#9 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#10 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#13 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#15 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#16 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#17 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#19 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#20 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#22 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#23 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#24 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#25 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#26 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#27 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#29 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#30 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#32 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#34 /Users/hello/laravel/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#36 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#38 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#40 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#41 /Users/hello/laravel/vendor/laravel/octane/src/ApplicationGateway.php(36): Illuminate\\Foundation\\Http\\Kernel->handle()
#42 /Users/hello/laravel/vendor/laravel/octane/src/Worker.php(92): Laravel\\Octane\\ApplicationGateway->handle()
#43 /Users/hello/laravel/vendor/jie-anthony/laravel-octane-workerman/bin/createHttpWorker.php(60): Laravel\\Octane\\Worker->handle()
#44 /Users/hello/laravel/vendor/workerman/workerman/Connection/TcpConnection.php(638): {closure}()
#45 /Users/hello/laravel/vendor/workerman/workerman/Events/Select.php(311): Workerman\\Connection\\TcpConnection->baseRead()
#46 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(2463): Workerman\\Events\\Select->loop()
#47 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1574): Workerman\\Worker->run()
#48 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1416): Workerman\\Worker::forkOneWorkerForLinux()
#49 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1390): Workerman\\Worker::forkWorkersForLinux()
#50 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1720): Workerman\\Worker::forkWorkers()
#51 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1660): Workerman\\Worker::monitorWorkersForLinux()
#52 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(559): Workerman\\Worker::monitorWorkers()
#53 /Users/hello/laravel/vendor/jie-anthony/laravel-octane-workerman/bin/gatewayworker-server(81): Workerman\\Worker::runAll()
#54 {main}

[previous exception] [object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:7050/oauth/token at /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210)
[stacktrace]
#0 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1095): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1061): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#7 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(1047): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#8 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#9 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Middleware.php(37): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#10 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#11 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Middleware.php(61): GuzzleHttp\\RedirectMiddleware->__invoke()
#12 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#13 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke()
#14 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer()
#15 /Users/hello/laravel/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync()
#16 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(905): GuzzleHttp\\Client->request()
#17 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(779): Illuminate\\Http\\Client\\PendingRequest->sendRequest()
#18 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Support/helpers.php(243): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}()
#19 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(817): retry()
#20 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(686): Illuminate\\Http\\Client\\PendingRequest->send()
#21 /Users/hello/laravel/app/Qingwuit/Services/AuthService.php(75): Illuminate\\Http\\Client\\PendingRequest->post()
#22 /Users/hello/laravel/app/Http/Controllers/Auth/AuthController.php(17): App\\Qingwuit\\Services\\AuthService->login()
#23 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Auth\\AuthController->login()
#24 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#25 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#26 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#27 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#28 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#29 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#31 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(102): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#33 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(54): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#34 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#35 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#37 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#38 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#40 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#42 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#43 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#44 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#48 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#50 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#52 /Users/hello/laravel/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#54 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#56 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#58 /Users/hello/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#59 /Users/hello/laravel/vendor/laravel/octane/src/ApplicationGateway.php(36): Illuminate\\Foundation\\Http\\Kernel->handle()
#60 /Users/hello/laravel/vendor/laravel/octane/src/Worker.php(92): Laravel\\Octane\\ApplicationGateway->handle()
#61 /Users/hello/laravel/vendor/jie-anthony/laravel-octane-workerman/bin/createHttpWorker.php(60): Laravel\\Octane\\Worker->handle()
#62 /Users/hello/laravel/vendor/workerman/workerman/Connection/TcpConnection.php(638): {closure}()
#63 /Users/hello/laravel/vendor/workerman/workerman/Events/Select.php(311): Workerman\\Connection\\TcpConnection->baseRead()
#64 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(2463): Workerman\\Events\\Select->loop()
#65 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1574): Workerman\\Worker->run()
#66 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1416): Workerman\\Worker::forkOneWorkerForLinux()
#67 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1390): Workerman\\Worker::forkWorkersForLinux()
#68 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1720): Workerman\\Worker::forkWorkers()
#69 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(1660): Workerman\\Worker::monitorWorkersForLinux()
#70 /Users/hello/laravel/vendor/workerman/workerman/Worker.php(559): Workerman\\Worker::monitorWorkers()
#71 /Users/hello/laravel/vendor/jie-anthony/laravel-octane-workerman/bin/gatewayworker-server(81): Workerman\\Worker::runAll()
#72 {main}
```

**Comment by mouyong** [comment]
https://www.workerman.net/q/9067

可以参考 walkor 文中提到的：开启http服务。

复制一份 http 进程配置，然后将慢接口交给这些进程处理。

**Comment by mouyong** [comment]
https://www.workerman.net/q/9128 curl 请求属于阻塞这类的请求。

**Comment by mouyong** [comment]
https://www.workerman.net/q/4789 阻塞进程小伙伴们的经验

**Comment by mouyong** [comment]
已支持多 http 服务. #34

**Comment by jiangslee** [comment]
感谢大佬，解决方案:多开一个进程能解决，相当于多开一个`php artisan serve  --port 8001`，关贴了。
